- hosts: all
  sudo: yes

  tasks:
    - name: Set up rsync export for fedora-atomic
      action: ini_file
        dest=/etc/rsyncd.conf
        section=fedora-atomic option=path
        value=/srv/fedora-atomic/output

    - service: name=rsyncd enabled=yes state=started
      


