- hosts: all
  sudo: yes

  vars:
    datadir: /srv/fedora-atomic
    outputdir: "{{ datadir }}/output"
    inboxdir: /srv/fedora-atomic/inbox

  tasks:
    - name: Determine if we have EPEL 7
      command: "/bin/sh -c 'test -f /etc/yum.repos.d/epel.repo || test -f /etc/yum.repos.d/epel7.repo'"
      register: have_epel7

    - name: copy EPEL 7 rpm
      action: copy src=files/epel-release-7-2.noarch.rpm
              dest=/root/epel-release.rpm
              owner=root group=root
      when: not have_epel7

    - yum: name=/root/epel-release.rpm state=present
      when: not have_epel7

    - name: add CentOS 7 Virt Testing
      action: copy src=files/centos-7-virt-testing.repo
              dest=/etc/yum.repos.d/centos-7-virt-testing.repo
              owner=root group=root

    - name: add CentOS 7 Atomic Testing
      action: copy src=files/centos-7-atomic-testing.repo
              dest=/etc/yum.repos.d/centos-7-atomic-testing.repo
              owner=root group=root

    - yum: name={{ item }} state=present
      with_items:
        - git
        - ostree
        - rpm-ostree
        - rpm-ostree-toolbox
        - docker
        - docker-registry

    - service: name=docker.service enabled=yes state=started

    - service: name=libvirtd.socket enabled=yes state=started

    - name: Create output directory
      file: path={{ outputdir }} setype=public_content_t recurse=yes
            state=directory

    - name: Create output images dir
      file: path={{ outputdir }}/images
            state=directory

    - name: Create output repo dir
      file: path={{ outputdir }}/repo
            owner=root group=root mode=755 state=directory

    - command: /usr/bin/ostree init --repo={{ outputdir }}/repo --mode=archive-z2
      args:
        creates: "{{ outputdir }}/repo/objects"

    - file: path={{ inboxdir }}
            owner=root group=rpmostreecompose mode=775 state=directory

    - yum: name={{ item }} state=present
      with_items:
        - httpd
